### ISSUE TITLE
Feature Request: Gradle DSL for Cabal

### ISSUE THREAD

**Issue by EarthCitizen** [typelead/gradle-eta#1]
In order to create a more Gradle-centric experience, and to avoid having multiple files for build configuration, it would be great to have a DSL in the build.gradle to represent the Cabal settings.

A possibility is to have the DSL definable at the root project level and sub-project level, then to only need to declare the settings needed as overrides in the sub-project.

What I would NOT do though, is put dependencies in this DSL. I would put the Haskell-only dependencies in an Eta-specific configuration so that they can be in the dependencies section of the build.gradle, as is typical.

**Comment by carymrobbins** [comment]
This is exactly what I want as well. Since you were gracious enough to submit the issue, I may use you as a resource to bounce ideas off of to ensure this comes out as idomatic as possible.

**Comment by EarthCitizen** [comment]
Sure! And as it happens, I have experience implementing a DSL in Gradle. So, more than happy to give input.

**Comment by rahulmutt** [comment]
@EarthCitizen The Gradle DSL is in place now - it allows you to specify Hackage dependencies like so:
```gradle
dependencies {
  eta {
    compile 'text:1.2.2.2'
  }
}
```

We will do a release within a week or two. Currently resolving some minor bugs. Multi-module Eta builds should work using `project(':[project-name]')` dependency notation that Gradle users are familiar with.

**Comment by EarthCitizen** [comment]
@rahulmutt Is there a reason that the dependencies are in their own container rather than being in the eta scope?

I would have expected something like this:
```
dependencies {
    eta ’text:1.2.3.4'
    etaTest 'somedep:1.2.3.4'
}
```
I belive that is more idiomadic Gradle. This is also what other plugins do like the Gradle JRuby plugin:
```
dependencies {
    gem 'something:1.2.3'
}
```

**Comment by rahulmutt** [comment]
@EarthCitizen Part of the reason is that the Eta compilation tasks use the same configuration as the Java compilation task - `compileClasspath` configuration when compiling + the path to the `classes` directory generated by the Java task. The goal was to make things as transparent as possible without having to learn about new conventions. By doing this, all the Eta dependencies (as jars) are available to the Java task so that you can use the Eta generated classes in your Java code if you need to.

Take for example, the Scala plugin, which doesn't define new configurations specific for Scala. It instead piggy-backs on the configurations defined by the Java plugin. Groovy does something similar. Both the Scala plugin and Groovy plugin were used as references when implementing the Eta plugin.

I'm not sure whether to go with the JRuby way or the Scala/Groovy way - what are the pros/cons of each?

**Comment by EarthCitizen** [comment]
One of the most important cons is that it is not conventional to have an additional sub-block in the dependencies block.

Here is a solution that may make Eta dependencies idiomatic to Gradle and still allow you to piggyback on the Java configuration:

```gradle
dependencies {
    compile eta('text:1.2.3.4')
    testCompile eta('hspec:1.2.3.4')
}
```
In this case, `eta()` returns an implementation of:
`org.gradle.api.artifacts.SelfResolvingDependency`

And would be added with:
`project.dependencies.ext.eta = <eta method impl>`

**Comment by rahulmutt** [comment]
@EarthCitizen That looks awesome. It looks a lot cleaner.

But there is one tricky bit here: resolving Eta dependencies can spit out two kinds of outputs: 1) a set of jars that represents the transitive dependency closure 2) a set of maven dependencies that have yet to be resolved. The 2nd scenario can occur if we use a Java library to patch a Hackage package. So I'm not sure that `SelfResolvingDependency` will be enough. Is there something like `CompositeDependency`?

The current implementation uses an `installDependenciesEta` task which will work through all the dependencies defined in an `eta` block and resolve them and dynamically inject the maven dependencies + jar file dependencies to the corresponding configurations. I've setup the task dependency ordering carefully so that this task occurs before any configuration is resolved.

**Comment by rahulmutt** [comment]
If `eta()` returns `List<Dependency>` will `compile eta(...)` still work as expected?

EDIT: Scratch that, let's say it returned `Object[]` where `Object` can be multiple types of dependency notations.

**Comment by EarthCitizen** [comment]
It looks like `eta()` returning something other than an implementation of the `Dependency` interface should work:

https://docs.gradle.org/current/userguide/dependency_types.html

But, I suppose you could also implement your own `EtaCompositeDependency` type from the `Dependency` interface. It may be necessary to dig into the Gradle source to understand how they handle the various `Dependency` interfaces (all of which are public API) as Gradle does `instanceof` checks:

https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Dependency.html

**Comment by EarthCitizen** [comment]
But thinking about it more, I think returning multiple things would be easier, as long as this works:

`compile 'something:something:1.2.3', gradleApi(), project(':sub-project')`

If that works, then you could return from `eta()` local jars, maven jars, and anything else needed in one go. Assuming that I am understanding the problem correctly.

**Comment by EarthCitizen** [comment]
Another strategy is to use a detached configuration:

`eta()`:
```gradle
final dep1 = project.dependencies.create('some:maven:dep')
final dep2 = project.dependencies.create('some:maven:dep')

final config = project.configurations.detachedConfiguration(dep1, dep2)
final depJarFiles = config.resolve()
final hackageJar = <download, build>

return project.files(depJarFiels + hackageJar
```

**Comment by EarthCitizen** [comment]
I guess the tricky part is that you make Gradle aware of the transitive dependencies that you are pulling in so that it can do proper dependency graph analysis.

**Comment by rahulmutt** [comment]
Yeah. I figured out a hacky way to get the UI we want - `eta()` returns a custom `SelfResolvingDependency` which contains extra metadata containing Eta-specific info, but returns an empty `FileCollection`. All the configurations will have some extra logic every time a new Eta dependency gets added that will populate the `EtaConfiguration` that is attached to every `Configuration`. Then the rest of the story is the same as it has been so far.

**Comment by rahulmutt** [comment]
Btw, for specifying Eta dependencies from Git, how does this look:
```gradle
dependencies {
  compile eta(package: 'eta-java-interop',
              location: 'git@github.com/typelead/eta-java-interop',
              commit: '7bc1df8f14720611b7cf374fcc502d6479a48517')
}
```

**Comment by EarthCitizen** [comment]
As a side note, I tried this and it works (what you were initially proposing of `eta()` returning multiple items):

```gradle
subprojects {
  apply plugin: 'java'
}

project(':otherproj').dependencies.ext.eta = {-> return ['org.slf4j:slf4j-api:1.7.22', project(':subproj'), fileTree("$project.rootDir/lib")]}

project(':subproj') {
  dependencies {
    compile 'org.slf4j:slf4j-api:1.7.22'
  }
}

project(':otherproj') {
  dependencies {
    compile eta()
  }

  task showClasspath {
    doLast {
      configurations.compile.each {
        println it
      }
    }
  }
}
```

```
$ gradle otherproj:dependencies --configuration compile
:otherproj:dependencies

------------------------------------------------------------
Project :otherproj
------------------------------------------------------------

compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
+--- org.slf4j:slf4j-api:1.7.22
\--- project :subproj
     \--- org.slf4j:slf4j-api:1.7.22

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL

Total time: 0.93 secs
```

```
$ gradle otherproj:showClasspath
:otherproj:showClasspath
/home/dir/project/dir/lib/commons-lang3-3.7.jar
/home/dir/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.22/a1c83373863cec7ae8d89dc1c5722d8cb6ec0309/slf4j-api-1.7.22.jar
/home/dir/project/dir/subproj/build/libs/subproj.jar

BUILD SUCCESSFUL

Total time: 30.565 secs
```

**Comment by EarthCitizen** [comment]
Git dependencies: looks good.

Does the syntax for Hackage change at all?

**Comment by rahulmutt** [comment]
Thanks for verifying that you can put multiple values in a dependency block! I'm currently in the process of implementing what I mentioned earlier.

**Comment by rahulmutt** [comment]
Done! I've implemented the `eta()` method. See https://github.com/typelead/gradle-eta/commit/0d480422117f43b277f782778c94f1a01bf4ca08 for the changes that were required. This change actually allowed me to delete lots of code.

Any more things you'd like to see in this plugin?

**Comment by rahulmutt** [comment]
> Does the syntax for Hackage change at all?

Which syntax are you referring to?

**Comment by EarthCitizen** [comment]
`eta('text:1.2.3.4')` pulling from Hackage

**Comment by EarthCitizen** [comment]
I see the new readme. Never mind. Question answered.

**Comment by EarthCitizen** [comment]
> Any more things you'd like to see in this plugin?

The user does not have to also maintain the cabal file, correct?

**Comment by rahulmutt** [comment]
Yes, no cabal file. It's generated for you by the Eta tasks.

**Comment by EarthCitizen** [comment]
Then I think this is good.

**Comment by rahulmutt** [comment]
Closing this as the DSL has been implemented. The examples cover how to configure language extensions, etc.
