### ISSUE TITLE
Gradle Run with Application plugin fails

### ISSUE THREAD

**Issue by NickSeagull** [typelead/gradle-eta#15]
When running `./gradlew run` with the Application plugin, it fails because doesn't find the `Closure` class.

I guess this is because Eta is not getting included in the classpath.

[Stacktrace here](https://gist.github.com/NickSeagull/1eebc748dadc5d0e28ec8be9adb08ddd)

**Comment by rahulmutt** [comment]
Can you try doing `./gradlew run` on `examples/multi` in this repo? For some odd reason the classpath works fine there, but it doesn't in other situations.

If you can share your project layout via some github repo that would be great. This seems like a tiny example that would be easier to debug.

**Comment by NickSeagull** [comment]
The `examples/multi` project fails with [this stacktrace](https://gist.github.com/NickSeagull/b5f9d600345af60d3eb4a59ed3b0d4a6)

You can see the project [in this repo](https://github.com/nickseagull/eta-ws) :smile:

**Comment by rahulmutt** [comment]
@NickSeagull Which commit of the gradle plugin did you build with? I am unable to reproduce with the version in 7b2498f5785c0c3fd0f388e48b86ac7a020b8d8f.

**Comment by rahulmutt** [comment]
Regarding your `eta-ws` setup, you need to create a new project for the `java` project and add the Eta project as a project dependency. In a single project, the dependencies can only go in the direction Java -> Eta direction when the `eta` plugin is enabled for that project. This is because it's common to write "FFI helpers" that do some small bit of work that would be cumbersome to import into Eta otherwise.

**Comment by NickSeagull** [comment]
I'm in the same commit as you @rahulmutt . Thanks, will create another project, and do what you said :smile:

**Comment by NickSeagull** [comment]
Just pushed new commits @rahulmutt , still same stacktrace.

What I did was create a new project and added the generated Jar as a dependency. Maybe Gradle is not generating an Uberjar?

**Comment by rahulmutt** [comment]
@NickSeagull Gradle doesn't generate an uberjar by default. If you setup a mulit-project build it should work. I'll send a PR with the setup I had in mind.

**Comment by rahulmutt** [comment]
So it turns out that the current mechanism Eta uses to inject dependencies via `files('...')` breaks down with project dependencies which don't include the file dependencies, hence why the classpath is broken when you do `project(':[proj]')` dependencies. The reason it worked for `examples/multi` was that we depended on an exported function that happens to be included in the compiled jar that Gradle automatically includes.

The solution to this (for now) is for the Eta plugin to maintain its own local Maven repository.

**Comment by rahulmutt** [comment]
This is a high priority bug - will fix it within the next couple of days. The layout for local maven repos seems simple so it should hopefully not take that long.

**Comment by rahulmutt** [comment]
@NickSeagull This should be fixed with commit `ac499aa8c0ccfff8f631eaf0cbb5da24edfcf933`. I've sent a PR to `eta-ws` as well.

**Comment by NickSeagull** [comment]
Thanks @rahulmutt , I did a `git pull` and rebuilt `gradle-eta` again, but the build now fails with another error:

[Stacktrace](https://gist.github.com/NickSeagull/6197a68bef0c3d1db5121e030ce30069)

**Comment by rahulmutt** [comment]
Hmm that seems to be the same error from before. Can you add the following diff locally and share the output of `./gradlew run --stacktrace -i`?
```
--- a/src/main/java/com/typelead/gradle/utils/ImmutableDAG.java
+++ b/src/main/java/com/typelead/gradle/utils/ImmutableDAG.java
@@ -81,7 +81,13 @@ public class ImmutableDAG<K,V> {
         for (K key : keys) {
             if (!excludedKeys.contains(key)) {
                 traversed.add(key);
-                queue.offer(graph.get(key));
+                System.out.println("ImmutableDAG: Initializing with: " + key);
+                V value = graph.get(key);
+                if (value == null) {
+                    System.out.println("ImmutableDAG: Failed to initialize null-valued key " + key);
+                    System.out.println(graph);
+                }
+                queue.offer(value);
             }
         }
```

**Comment by NickSeagull** [comment]
I cannot seem to be able to build with that patch applied:

```text
λ ~/Build/gradle-eta/ master* git apply rah.diff
λ ~/Build/gradle-eta/ master* ./gradlew pTML
:generatePomFileForPluginMavenPublication
:compileJava/home/nick/Build/gradle-eta/src/main/java/com/typelead/gradle/utils/ImmutableDAG.java:85: error: incompatible types: NodeInfo<K,V> cannot be converted to V
                V value = graph.get(key);
                                   ^
  where K,V are type-variables:
    K extends Object declared in class ImmutableDAG
    V extends Object declared in class ImmutableDAG
/home/nick/Build/gradle-eta/src/main/java/com/typelead/gradle/utils/ImmutableDAG.java:90: error: incompatible types: V cannot be converted to NodeInfo<K,V>
                queue.offer(value);
                            ^
  where V,K are type-variables:
    V extends Object declared in class ImmutableDAG
    K extends Object declared in class ImmutableDAG
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors
 FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
2 actionable tasks: 2 executed
```

**Comment by rahulmutt** [comment]
Sorry about that, here's the working one:
```
--- a/src/main/java/com/typelead/gradle/utils/ImmutableDAG.java
+++ b/src/main/java/com/typelead/gradle/utils/ImmutableDAG.java
@@ -81,7 +81,13 @@ public class ImmutableDAG<K,V> {
         for (K key : keys) {
             if (!excludedKeys.contains(key)) {
                 traversed.add(key);
-                queue.offer(graph.get(key));
+                System.out.println("ImmutableDAG: Initializing with: " + key);
+                NodeInfo<K,V> nodeInfo = graph.get(key);
+                if (nodeInfo == null) {
+                    System.out.println("ImmutableDAG: Failed to initialize null-valued key " + key);
+                    System.out.println(graph);
+                }
+                queue.offer(nodeInfo);
             }
         }
 
```

**Comment by NickSeagull** [comment]
There you go, thanks!

[stacktrace -i](https://gist.github.com/NickSeagull/55e2c9f7b4ebe3428d9cb9f2fab96323)

**Comment by rahulmutt** [comment]
Can you try building from the current `master` and trying again? I just realized the output of `etlas deps` is the old format which the plugin doesn't recognize anymore. It should work then.

**Comment by rahulmutt** [comment]
Current `master` of the Eta repo, that is.

**Comment by NickSeagull** [comment]
Thanks, works now! Closing :smile:
