### ISSUE TITLE
gradlew build task fail for some of the example projects

### ISSUE THREAD

**Issue by pedantic79** [typelead/gradle-eta#18]
The build task is normally used to compile and run the test for any gradle based projects. But most of the examples do not run correctly because of problems with the tests.

- fatjar -- etlas fails with `  unknown package: fatjar (dependency of fatjar-test-0.0.0)`
- multi -- etlas fails with `  unknown package: multi (dependency of multi-test-0.0.0)`
- simple -- only works because [simple package](https://hackage.haskell.org/package/simple) exists to meet the dependency
- test --  seems to work because it does not include the application plugin

**Comment by rahulmutt** [comment]
@pedantic79 Thanks for reporting this! We will look into it.

**Comment by rahulmutt** [comment]
Fixed in `0.6.6`.
