### ISSUE TITLE
Append .exe to Windows binaries

### ISSUE THREAD

**Issue by carymrobbins** [typelead/gradle-eta#4]
From [Gitter](https://gitter.im/typelead/eta?at=59fb2799e44c43700aab6ed1)

> Psybur
> When running gradlew compileEta Im getting this: > Failed to fetch file from url: http://88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com/etlas-1.0.2.0/binaries/x86_64-windows/etlas
>
> Rahul Muttineni
> That url should be http://88a2a1b21f8e03a6bc8d-8f2e61d843ea88e4f30ab3f81ca0e396.r42.cf5.rackcdn.com/etlas-1.0.2.0/binaries/x86_64-windows/etlas.exe

In the same way that we do a platform check in [EtlasBinaryDependencyResolver#resolveRemote](https://github.com/typelead/gradle-eta/blob/f003f908cfd51b3a8c129a3334701ba41bebb1cb/src/main/groovy/com/typelead/gradle/eta/dependency/EtlasBinaryDependencyResolver.java#L55-L57) we need to append `.exe` to binary names in [EtlasBinaryDependencyResolver#getEtlasUrlString](https://github.com/typelead/gradle-eta/blob/f003f908cfd51b3a8c129a3334701ba41bebb1cb/src/main/groovy/com/typelead/gradle/eta/dependency/EtlasBinaryDependencyResolver.java#L76).

**Comment by jrciii** [comment]
resolveInSystemPath() also needs to be modified. Perhaps others too, but can verify this one definitely needs it.

**Comment by carymrobbins** [comment]
@jrciii - I have a branch and PR out that should resolve this issue - [4-windows-binaries](https://github.com/typelead/gradle-eta/pull/6)

If you can, try it out and let me know if this works for you. Otherwise we can review and merge.

**Comment by carymrobbins** [comment]
I'm going to go ahead and close this for now, @jrciii please reopen if you encounter any issues with this moving forward.
